CREATE DATABASE [DW_DataBase]

USE DW_DataBase

CREATE TABLE [Product](
	Id INT IDENTITY(1,1) PRIMARY KEY,
	[Name] VARCHAR(300) UNIQUE NOT NULL,
	[Description] VARCHAR(2000),
	Maker VARCHAR(200)
)

CREATE TABLE [Client](
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdentificationNumber VARCHAR(10) UNIQUE NOT NULL,
	DocumentType VARCHAR(3) DEFAULT('CC'),
	FirstName VARCHAR(100) NOT NULL,
	SecondName VARCHAR(100) NULL,	
	Surname VARCHAR(100) NOT NULL,
	SecondSurname VARCHAR(100) NULL,
	BirthDate DATE NOT NULL
)

CREATE TABLE [Inventory](
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ProductId INT NOT NULL,
	UnitPrice DECIMAL(9,2) NOT NULL,
	Quantity INT DEFAULT(0),
	PurchaseDate DATETIME NOT NULL,
	FOREIGN KEY (ProductId) REFERENCES [Product](Id),
)

CREATE TABLE [Sales](
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ProductId INT NOT NULL,
	ClientId INT NOT NULL,
	SaleDate DATETIME NOT NULL,
	Quantity INT NOT NULL,
	FOREIGN KEY (ProductId) REFERENCES [Product](Id),
	FOREIGN KEY (ClientId) REFERENCES [Client](Id)
)